### ISSUE TITLE
Failing when commits made to file without extension

### ISSUE THREAD

**Issue by ritzz32** [hmcmanus/yaml-validator-hook#11]
Just ran into this. After activating this in bitbucket we made a commit to a file which does not have a file extension. Upon pushing the commit we received this error

`remote: Hook com.mcmanus.scm.stash.hook.YamlValidatorPreReceiveRepositoryHook failed. Error: 
remote: null`

After experimenting a little bit commits to our .yaml files and files with a different extension work just fine, however files without extensions always give this message.

**Comment by dk1983** [comment]
Duplicate of https://github.com/hmcmanus/yaml-validator-hook/issues/7

**Comment by hmcmanus** [comment]
Fixed in version 3.2.2
