### ISSUE TITLE
Support for multi-document YAML files

### ISSUE THREAD

**Issue by steve-oakey** [hmcmanus/yaml-validator-hook#13]
It may be as easy as changing [this line](https://github.com/hmcmanus/yaml-validator-hook/blob/master/src/main/java/com/mcmanus/scm/stash/hook/YamlValidatorPreReceiveRepositoryHook.java#L133) to call `loadAll`. I can provide a PR if you see no problem.

**Comment by hmcmanus** [comment]
Hey Steve, 

By all means please send a pull request. There is a shameful lack of tests in the plugin but lets do a bit of testing between us so that we have some confidence and I'll release a new version. 

Thanks,
Hugh

**Comment by Natanande** [comment]
Any update on this?

**Comment by cabbonizio** [comment]
Hi, was wondering if this will be implemented?   We support multi-document YAML files for our Spring Boot configuration and would be great if this plugin supported this.

**Comment by hmcmanus** [comment]
Hey, I'm going to work on this separate to the latest upgrade. I attempted it with the snake yaml library I was using and had limited success even though it was in the documentation. Needs more testing but will come after the bitbucket server 6 upgrade.

**Comment by 9numbernine9** [comment]
Hi @hmcmanus ! I've submitted PR #19 that I think provides this feature. Please feel free to take a look and let me know what you think. :-)

**Comment by hmcmanus** [comment]
Thanks @steve-oakey, I'll take a look this week and cut a release so that people can start using it. Thanks for the contribution.

**Comment by steve-oakey** [comment]
> Thanks @steve-oakey, I'll take a look this week and cut a release so that people can start using it. Thanks for the contribution.

Thank @9numbernine9!
