### ISSUE TITLE
Compatibility with Bitbucket 6

### ISSUE THREAD

**Issue by sigv** [hmcmanus/yaml-validator-hook#16]
We are planning on upgrading to Bitbucket 6, but the `yaml-validator-hook` app (version 3.2.2) has not been marked as compatible with Bitbucket 6.0.1, which is worrisome as we do use it for push checks and would like to be sure we do not cause breakage which could have been avoided with testing.

**Comment by hmcmanus** [comment]
Hey @sigv, I'll be working through the changes required to move to the new version, probably do a release for the bitbucket version 5 version then move to testing on the version 6 over the next week or so. I'll hopefully get a release completed in the next week for you to consume.

Apologies for the delay in response.

**Comment by sigv** [comment]
Happy to hear you are working on it. Don't sweat the delay!

**Comment by hmcmanus** [comment]
Hey @sigv , I've just released a new version of the plugin. Would you be able to test to make sure that everything is OK?

**Comment by sigv** [comment]
[Version History on Atlassian Marketplace](https://marketplace.atlassian.com/apps/1213552/yaml-validator-hook/version-history) seems to think the `3.3.0` release is older than the `3.2.2` and `3.2.3` releases. Universal Plugin Manager inside Bitbucket also seems to believe that. Is there possibly some version number that is wonky somewhere?

Current outlook for us is to carry out the upgrade to Bitbucket v6 over the second half of next week, but I have installed the `3.3.0` release with Bitbucket v5.16.3 right now and will see how that works. I will keep you posted.

**Comment by hmcmanus** [comment]
Yep, I'm having a bit of trouble with marketplace at the moment. I'll try to fix it up in the morning.

3.3.0 is the one I've tested Bitbucket 6 against. I'll try to sort out plufin manager so it's a better experience installing. Bear with me on this one. A few changes with licencing has made a bit more tricky. All still open source though 😁

**Comment by hmcmanus** [comment]
@sigv so worked it out in the end, it was because the build number of 3.2.3 was greater than that build number of 3.3.0. I didn't realise that took preference over the actual version of the plugin. Well that's something I've learned!

I've now released a new version with a higher build number so plugin manager should work now as well.

**Comment by sigv** [comment]
It seems Bitbucket Server `6.1.2` changed API compatibility once again?

**Comment by hmcmanus** [comment]
Not necessarily, the internal API compatibility should still be fine. This is more to do with the relationship with the plugin and Bitbucket versions. 

When I release a version of the plugin I need to choose the compatibility range. When new versions of the Bitbucket server come out I need to mark a version of the plugin to be compatible with that version of the Bitbucket server. There is no way to mark a plugin as compatible with for example 6.*.* version of Bitbucket - none that I'm aware of anyway.

**Comment by sigv** [comment]
Thank you for the mighty fine work.

To double-check then - it should be reasonable for us to upgrade to `6.1.2` and expect everything to still work regardless of the listing stating `5.9.1 - 6.1.1` compatibility?

**Comment by hmcmanus** [comment]
That's correct.

I would be more cautious moving major versions from 6.*.* to 7.*.*.

**Comment by sigv** [comment]
We have carried out the upgrade to `6.1.1` for now and will most likely roll up to `6.1.2` next week then. Thank you very much!
