### ISSUE TITLE
Bitbucket 7 support?

### ISSUE THREAD

**Issue by mss** [hmcmanus/yaml-validator-hook#34]
Hi @hmcmanus!

Thanks again for merging my PR for #25. I was about to open a ticket with the team maintaining the local Bitbucket instance but noticed that you bumped the version requirement to v8 whereas we are still running v7.21.

Is there any chance you could release/publish a v3.6 for Bitbucket v7 as well?

**Comment by hmcmanus** [comment]
Hi there,

Sorry I saw this and forgot to reply. I'll test it against the version 7 tomorrow and release a new version.

**Comment by mss** [comment]
@hmcmanus thanks! If you need any help with that feel free to ping me.

**Comment by hmcmanus** [comment]
Hey @mss I just realised that I didn't come back here and comment on this issue after I had released support for version 7. I hope you noticed it anyway. Closing this now as I have release version 4.1.3.

Any issue please reopen.

**Comment by mss** [comment]
Hey @hmcmanus! Thanks for the update. I actually didn't notice this yet so thanks for the heads up.
