### ISSUE TITLE
File Extension Field Always Shows 'yaml' Regardless of Current Value

### ISSUE THREAD

**Issue by 9numbernine9** [hmcmanus/yaml-validator-hook#9]
Hello!

I've recently installed this plugin on a BitBucket 4.11.1 server and it appears to work perfectly fine, but there seems to be one small UI-related issue: When you click on the button to configure the plugin for a given repo, the entry box for 'Yaml file extension' always shows the value 'yaml' regardless of whatever value was previously set. For example, if I set the value to 'ya?ml' and hit 'Save' and then click on the button to edit the plugin's configuration again, the value in that field will still be 'yaml' even though I just changed it. After setting the value to 'ya?ml' the plugin will correctly reject both invalid .yml _and_ .yaml files, but the plugin configuration will always show 'yaml' as the current value.

I realize this is a minor issue, but it would be nice to have addressed. :-)

**Comment by 9numbernine9** [comment]
Update: I did some debugging and this appears to be an easy fix. I've submitted PR #10 for your approval!

**Comment by hmcmanus** [comment]
Fixed in version 3.2.2
